### ISSUE TITLE
Exception while terminating the session 

### ISSUE THREAD

**Issue by ahmedsalamay** [Tap-Payments/gosellSDK-Flutter#16]
When calling terminateSession(); 

Flutter 1.22.2
SDK version:  go_sell_sdk_flutter: ^2.0.1
Platform: Android

system.out(20611): onMethodCall..... started
I/System.out(20611): terminate session!
E/MethodChannel#go_sell_sdk_flutter(20611): Failed to handle method call
E/MethodChannel#go_sell_sdk_flutter(20611): java.lang.NullPointerException: Attempt to invoke virtual method 'gotap.com.tapglkitandroid.gl.Views.TapLoadingView company.tap.gosellapi.open.buttons.PayButtonView.getLoadingView()' on a null object reference
E/MethodChannel#go_sell_sdk_flutter(20611): 	at company.tap.gosellapi.open.controllers.SDKSession.cancelSession(SDKSession.java:644)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at tap.company.go_sell_sdk_flutter.GoSellSdKDelegate.terminateSDKSession(GoSellSdKDelegate.java:65)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at tap.company.go_sell_sdk_flutter.GoSellSdkFlutterPlugin.onMethodCall(GoSellSdkFlutterPlugin.java:300)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
/MethodChannel#go_sell_sdk_flutter(20611): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#go_sell_sdk_flutter(20611): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (20611): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'gotap.com.tapglkitandroid.gl.Views.TapLoadingView company.tap.gosellapi.open.buttons.PayButtonView.getLoadingView()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'gotap.com.tapglkitandroid.gl.Views.TapLoadingView company.tap.gosellapi.open.buttons.PayButtonView.getLoadingView()' on a null object reference
E/flutter (20611): 	at company.tap.gosellapi.open.controllers.SDKSession.cancelSession(SDKSession.java:644)
E/flutter (20611): 	at tap.company.go_sell_sdk_flutter.GoSellSdKDelegate.terminateSDKSession(GoSellSdKDelegate.java:65)
E/flutter (20611): 	at tap.company.go_sell_sdk_flutter.GoSellSdkFlutterPlugin.onMethodCall(GoSellSdkFlutterPlugin.java:300)
E/flutter (20611): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (20611): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)

E/flutter (20611): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (20611): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (20611): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (20611): 	at android.os.Looper.loop(Looper.java:181)
E/flutter (20611): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/flutter (20611): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20611): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter (20611): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by mouni-eng** [comment]
hi there did you found a solution for this problem
