### ISSUE TITLE
Unable to destroy activity {com.carenal.app/com.carenal.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.Lifecycle.removeObserver(androidx.lifecycle.LifecycleObserver)' on a null object reference

### ISSUE THREAD

**Issue by Add00w** [Tap-Payments/gosellSDK-Flutter#25]
Flutter app crashes when we add gosellSDK  in dependences and run the app the press back button with the following error:

<details>
<summary>error log</summary>
<pre><code>
java.lang.RuntimeException: Unable to destroy activity {com.carenal.app/com.carenal.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.Lifecycle.removeObserver(androidx.lifecycle.LifecycleObserver)' on a null object reference
E/AndroidRuntime( 4404): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4383)
E/AndroidRuntime( 4404): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
E/AndroidRuntime( 4404): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
E/AndroidRuntime( 4404): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
E/AndroidRuntime( 4404): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4404): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4404): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime( 4404): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4404): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime( 4404): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime( 4404): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.Lifecycle.removeObserver(androidx.lifecycle.LifecycleObserver)' on a null object reference
E/AndroidRuntime( 4404): 	at tap.company.go_sell_sdk_flutter.GoSellSdkFlutterPlugin.tearDown(GoSellSdkFlutterPlugin.java:227)
E/AndroidRuntime( 4404): 	at tap.company.go_sell_sdk_flutter.GoSellSdkFlutterPlugin.onDetachedFromActivity(GoSellSdkFlutterPlugin.java:175)
E/AndroidRuntime( 4404): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:389)
E/AndroidRuntime( 4404): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:560)
E/AndroidRuntime( 4404): 	at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:587)
E/AndroidRuntime( 4404): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:608)
E/AndroidRuntime( 4404): 	at android.app.Activity.performDestroy(Activity.java:7218)
E/AndroidRuntime( 4404): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
E/AndroidRuntime( 4404): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
</code></pre>
</details>

**Comment by Add00w** [comment]
#26

**Comment by Add00w** [comment]
@kareem5 @tappayments @olamonir @halaq
